name: "Tauri App Publish"

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          # - platform: 'macos-14' # for Arm based macs (M1 and above).
          #   args: '--target aarch64-apple-darwin --verbose'
          # - platform: 'macos-14' # for Intel based macs.
          #   args: '--target x86_64-apple-darwin --verbose'
          # - platform: "macos-14" # for Both Arm and Intel based macs.
          #   args: "--target universal-apple-darwin --verbose"
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: "--verbose"
          - platform: 'windows-latest'
            args: "--verbose"

    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: install dependencies (ubuntu only)
        if: matrix.settings.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: pnpm/action-setup@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm" # Set this to npm, yarn or pnpm.
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.settings.platform == 'macos-14' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: Add rust target (macos only)
        if: matrix.settings.platform == 'macos-14'
        run: |
          rustup target add aarch64-apple-darwin
          rustup target add x86_64-apple-darwin

      - run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: Jarvis-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "Jarvis v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.settings.args }}
